/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.isnakegame;

import java.awt.*;

/**
 *
 * @author Ibrahim
 */
public class LeaderBoards extends javax.swing.JPanel {

    /**
     * Creates new form LeaderBoards
     */
    public LeaderBoards() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Num4 = new javax.swing.JLabel();
        Num5 = new javax.swing.JLabel();
        Num6 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        goBackText = new javax.swing.JLabel();
        goBackBtn = new javax.swing.JLabel();
        underLogo = new javax.swing.JLabel();
        Num3 = new javax.swing.JLabel();
        Num2 = new javax.swing.JLabel();
        Num1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        backgrnd = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Num4.setFont(new java.awt.Font("Poppins", 1, 55)); // NOI18N
        Num4.setForeground(new java.awt.Color(255, 210, 85));
        Num4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Num4.setText("22");
        add(Num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 90, 80));

        Num5.setFont(new java.awt.Font("Poppins", 1, 55)); // NOI18N
        Num5.setForeground(new java.awt.Color(255, 210, 85));
        Num5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Num5.setText("45");
        add(Num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 320, 100, 70));

        Num6.setFont(new java.awt.Font("Poppins", 1, 55)); // NOI18N
        Num6.setForeground(new java.awt.Color(255, 210, 85));
        Num6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Num6.setText("53");
        add(Num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 210, 100, 80));

        name3.setFont(new java.awt.Font("Poppins", 1, 55)); // NOI18N
        name3.setForeground(new java.awt.Color(255, 255, 255));
        name3.setText("IBRAHIM");
        add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, 50));

        name2.setFont(new java.awt.Font("Poppins", 1, 55)); // NOI18N
        name2.setForeground(new java.awt.Color(255, 255, 255));
        name2.setText("MOHAMED");
        add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, 50));

        name1.setFont(new java.awt.Font("Poppins", 1, 55)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("IBRAHIM");
        add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, 60));

        goBackText.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        goBackText.setForeground(new java.awt.Color(255, 255, 255));
        goBackText.setText("GO BACK");
        add(goBackText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, 50));

        goBackBtn.setIcon(new javax.swing.ImageIcon("D:\\My PC\\Projects\\Java\\Snake\\iSnakeGame\\src\\main\\java\\com\\mycompany\\Stokes\\btn.png")); // NOI18N
        goBackBtn.setText("jLabel1");
        goBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goBackBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goBackBtnMouseExited(evt);
            }
        });
        add(goBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 260, 50));

        underLogo.setIcon(new javax.swing.ImageIcon("D:\\My PC\\Projects\\Java\\Snake\\iSnakeGame\\src\\main\\java\\com\\mycompany\\Stokes\\underwinlogo.png")); // NOI18N
        add(underLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 610, 40, 30));

        Num3.setFont(new java.awt.Font("Poppins", 1, 75)); // NOI18N
        Num3.setForeground(new java.awt.Color(255, 255, 255));
        Num3.setText("03");
        add(Num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, 80));

        Num2.setFont(new java.awt.Font("Poppins", 1, 75)); // NOI18N
        Num2.setForeground(new java.awt.Color(255, 255, 255));
        Num2.setText("02");
        add(Num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 80));

        Num1.setFont(new java.awt.Font("Poppins", 1, 75)); // NOI18N
        Num1.setForeground(new java.awt.Color(255, 255, 255));
        Num1.setText("01");
        add(Num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 80));

        title.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 210, 85));
        title.setText("L E A D E R  B O A R D S");
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 530, 50));

        backgrnd.setIcon(new javax.swing.ImageIcon("D:\\My PC\\Projects\\Java\\Snake\\iSnakeGame\\src\\main\\java\\com\\mycompany\\Stokes\\leaderboards.png")); // NOI18N
        add(backgrnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 650));
    }// </editor-fold>//GEN-END:initComponents

    
    /*
    button hover
    */
    private void goBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseClicked
        GameFrame.goBack();
    }//GEN-LAST:event_goBackBtnMouseClicked

    private void goBackBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseEntered
        goBackText.setForeground(Color.BLACK);
    }//GEN-LAST:event_goBackBtnMouseEntered

    
    /*
    Button Actions
    */
    
    private void goBackBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackBtnMouseExited
        goBackText.setForeground(Color.WHITE);
    }//GEN-LAST:event_goBackBtnMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Num1;
    private javax.swing.JLabel Num2;
    private javax.swing.JLabel Num3;
    private javax.swing.JLabel Num4;
    private javax.swing.JLabel Num5;
    private javax.swing.JLabel Num6;
    private javax.swing.JLabel backgrnd;
    private javax.swing.JLabel goBackBtn;
    private javax.swing.JLabel goBackText;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel title;
    private javax.swing.JLabel underLogo;
    // End of variables declaration//GEN-END:variables
}
