/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.isnakegame;

import java.awt.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Ibrahim
 */
public class MainMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuPanel
     */
    public MainMenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitText = new javax.swing.JLabel();
        creidtsText = new javax.swing.JLabel();
        highScoreText = new javax.swing.JLabel();
        playText = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JLabel();
        creditsBtn = new javax.swing.JLabel();
        highScoreBtn = new javax.swing.JLabel();
        playBtn1 = new javax.swing.JLabel();
        MmPanelLogo = new javax.swing.JLabel();
        MmPanelBackGrd = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitText.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        exitText.setForeground(new java.awt.Color(255, 255, 255));
        exitText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitText.setText("E X I T");
        add(exitText, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 540, -1, 30));

        creidtsText.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        creidtsText.setForeground(new java.awt.Color(255, 255, 255));
        creidtsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creidtsText.setText("C R I E D T S");
        add(creidtsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 457, -1, -1));

        highScoreText.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        highScoreText.setForeground(new java.awt.Color(255, 255, 255));
        highScoreText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highScoreText.setText("H I G H   S C O R E ");
        add(highScoreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        playText.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        playText.setForeground(new java.awt.Color(255, 255, 255));
        playText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playText.setText("P L A Y");
        add(playText, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 283, -1, -1));

        ExitBtn.setIcon(new javax.swing.ImageIcon("D:\\My PC\\Projects\\Java\\Snake\\iSnakeGame\\src\\main\\java\\com\\mycompany\\Stokes\\btn.png")); // NOI18N
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtnMouseExited(evt);
            }
        });
        add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 260, 50));

        creditsBtn.setIcon(new javax.swing.ImageIcon("D:\\My PC\\Projects\\Java\\Snake\\iSnakeGame\\src\\main\\java\\com\\mycompany\\Stokes\\btn.png")); // NOI18N
        creditsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creditsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creditsBtnMouseExited(evt);
            }
        });
        add(creditsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 260, 50));

        highScoreBtn.setIcon(new javax.swing.ImageIcon("D:\\My PC\\Projects\\Java\\Snake\\iSnakeGame\\src\\main\\java\\com\\mycompany\\Stokes\\btn.png")); // NOI18N
        highScoreBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                highScoreBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                highScoreBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                highScoreBtnMouseExited(evt);
            }
        });
        add(highScoreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 363, 260, 50));

        playBtn1.setIcon(new javax.swing.ImageIcon("D:\\My PC\\Projects\\Java\\Snake\\iSnakeGame\\src\\main\\java\\com\\mycompany\\Stokes\\btn.png")); // NOI18N
        playBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playBtn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playBtn1MouseExited(evt);
            }
        });
        add(playBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 276, 260, 50));

        MmPanelLogo.setIcon(new javax.swing.ImageIcon("D:\\My PC\\Projects\\Java\\Snake\\iSnakeGame\\src\\main\\java\\com\\mycompany\\Stokes\\SecondFrameLogo.png")); // NOI18N
        MmPanelLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(MmPanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 52, 210, 190));

        MmPanelBackGrd.setIcon(new javax.swing.ImageIcon("D:\\My PC\\Projects\\Java\\Snake\\iSnakeGame\\src\\main\\java\\com\\mycompany\\Stokes\\SecondFrameBackground.png")); // NOI18N
        add(MmPanelBackGrd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 650));
    }// </editor-fold>//GEN-END:initComponents

    
   /*
    
    Button hovers
    
    */
    
    private void playBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBtn1MouseEntered
        playText.setForeground(Color.BLACK);
    }//GEN-LAST:event_playBtn1MouseEntered

    private void playBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBtn1MouseExited
        playText.setForeground(Color.WHITE);
    }//GEN-LAST:event_playBtn1MouseExited

    private void highScoreBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highScoreBtnMouseEntered
        highScoreText.setForeground(Color.BLACK);
    }//GEN-LAST:event_highScoreBtnMouseEntered

    private void highScoreBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highScoreBtnMouseExited
        highScoreText.setForeground(Color.WHITE);
    }//GEN-LAST:event_highScoreBtnMouseExited

    private void creditsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsBtnMouseEntered
        creidtsText.setForeground(Color.BLACK);
    }//GEN-LAST:event_creditsBtnMouseEntered

    private void creditsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsBtnMouseExited
        creidtsText.setForeground(Color.WHITE);
    }//GEN-LAST:event_creditsBtnMouseExited

    private void ExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseEntered
        exitText.setForeground(Color.RED);
    }//GEN-LAST:event_ExitBtnMouseEntered

    private void ExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseExited
        exitText.setForeground(Color.WHITE);
    }//GEN-LAST:event_ExitBtnMouseExited

    /*
    
    Button Actions
    
    */
    
    private void creditsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsBtnMouseClicked
           GameFrame.showCredits();
    }//GEN-LAST:event_creditsBtnMouseClicked

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        int n = JOptionPane.showConfirmDialog(null,"Are you sure you want to exit the fantastic iSnake?","Please don't go",JOptionPane.YES_NO_OPTION);
        if (n == 0)
            System.exit(0);
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void highScoreBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highScoreBtnMouseClicked
        GameFrame.showLeaderBoards();
    }//GEN-LAST:event_highScoreBtnMouseClicked

    private void playBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBtn1MouseClicked
        new GamePanel();
    }//GEN-LAST:event_playBtn1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitBtn;
    private javax.swing.JLabel MmPanelBackGrd;
    private javax.swing.JLabel MmPanelLogo;
    private javax.swing.JLabel creditsBtn;
    private javax.swing.JLabel creidtsText;
    private javax.swing.JLabel exitText;
    private javax.swing.JLabel highScoreBtn;
    private javax.swing.JLabel highScoreText;
    private javax.swing.JLabel playBtn1;
    private javax.swing.JLabel playText;
    // End of variables declaration//GEN-END:variables
}
